#!/usr/bin/env bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

sudo apt install -y nodejs
sudo apt install -y npm
sudo npm install -g yarn
sudo npm install d3
sudo apt-get install -y python3.8 python3-pip python3-venv
sudo apt-get install -y postgresql

# Heroku CLI
sudo curl https://cli-assets.heroku.com/install.sh | sh

cd server
# Python virtual environment
python3 -m venv ${DIR}/../server/pythonvenv
source ${DIR}/../server/pythonvenv/bin/activate
# Install python dependencies
pip install wheel
pip install -r requirements.txt
deactivate
